package com.archtranslator;

public enum Languages
{
	af("af", "Afrikaans"),
	ak("ak", "Twi"),
	am("am", "Amharic"),
	ar("ar", "Arabic"),
	as("as", "Assamese"),
	ay("ay", "Aymara"),
	az("az", "Azerbaijani"),
	be("be", "Belarusian"),
	bg("bg", "Bulgarian"),
	bho("bho", "Bhojpuri"),
	bm("bm", "Bambara"),
	bn("bn", "Bengali"),
	bs("bs", "Bosnian"),
	ca("ca", "Catalan"),
	ceb("ceb", "Cebuano"),
	ckb("ckb", "Kurdish (Sorani)"),
	co("co", "Corsican"),
	cs("cs", "Czech"),
	cy("cy", "Welsh"),
	da("da", "Danish"),
	de("de", "German"),
	doi("doi", "Dogri"),
	dv("dv", "Divehi"),
	ee("ee", "Ewe"),
	el("el", "Greek"),
	en("en", "English"),
	en_GB("en-GB", "English (British)"),
	en_US("en-US", "English (American)"),
	eo("eo", "Esperanto"),
	es("es", "Spanish"),
	et("et", "Estonian"),
	eu("eu", "Basque"),
	fa("fa", "Persian"),
	fi("fi", "Finnish"),
	fr("fr", "French"),
	fy("fy", "Frisian"),
	ga("ga", "Irish Gaelic"),
	gd("gd", "Scots Gaelic"),
	gl("gl", "Galician"),
	gn("gn", "Guarani"),
	gom("gom", "Konkani"),
	gu("gu", "Gujarati"),
	ha("ha", "Hausa"),
	haw("haw", "Hawaiian"),
	he("he", "Hebrew"),
	hi("hi", "Hindi"),
	hmn("hmn", "Hmong"),
	hr("hr", "Croatian"),
	ht("ht", "Haitian Creole"),
	hu("hu", "Hungarian"),
	hy("hy", "Armenian"),
	id("id", "Indonesian"),
	ig("ig", "Igbo"),
	ilo("ilo", "Iloko"),
	is("is", "Icelandic"),
	it("it", "Italian"),
	iw("iw", "Hebrew"),
	ja("ja", "Japanese"),
	jv("jv", "Javanese"),
	jw("jw", "Javanese"),
	ka("ka", "Georgian"),
	kk("kk", "Kazakh"),
	km("km", "Khmer"),
	kn("kn", "Kannada"),
	ko("ko", "Korean"),
	kri("kri", "Krio"),
	ku("ku", "Kurdish (Kurmanji)"),
	ky("ky", "Kyrgyz"),
	la("la", "Latin"),
	lb("lb", "Luxembourgish"),
	lg("lg", "Ganda"),
	ln("ln", "Lingala"),
	lo("lo", "Lao"),
	lt("lt", "Lithuanian"),
	lus("lus", "Mizo"),
	lv("lv", "Latvian"),
	mai("mai", "Maithili"),
	mg("mg", "Malagasy"),
	mi("mi", "Maori"),
	mk("mk", "Macedonian"),
	ml("ml", "Malayalam"),
	mn("mn", "Mongolian"),
	mni_MTEI("mni-MTEI", "Meiteilon (Manipuri)"),
	mr("mr", "Marathi"),
	ms("ms", "Malay"),
	mt("mt", "Maltese"),
	my("my", "Myanmar (Burmese)"),
	nb("nb", "Norwegian"),
	ne("ne", "Nepali"),
	nl("nl", "Dutch"),
	no("no", "Norwegian"),
	nso("nso", "Northern Sotho"),
	ny("ny", "Chichewa"),
	om("om", "Oromo"),
	or("or", "Odia (Oriya)"),
	pa("pa", "Punjabi"),
	pl("pl", "Polish"),
	ps("ps", "Pashto"),
	pt("pt", "Portuguese"),
	pt_BR("pt-BR", "Portuguese (Brazilian)"),
	pt_PT("pt-PT", "Portuguese (European)"),
	qu("qu", "Quechua"),
	ro("ro", "Romanian"),
	ru("ru", "Russian"),
	rw("rw", "Kinyarwanda"),
	sa("sa", "Sanskrit"),
	sd("sd", "Sindhi"),
	si("si", "Sinhala"),
	sk("sk", "Slovak"),
	sl("sl", "Slovenian"),
	sm("sm", "Samoan"),
	sn("sn", "Shona"),
	so("so", "Somali"),
	sq("sq", "Albanian"),
	sr("sr", "Serbian"),
	st("st", "Sesotho"),
	su("su", "Sundanese"),
	sv("sv", "Swedish"),
	sw("sw", "Swahili"),
	ta("ta", "Tamil"),
	te("te", "Telugu"),
	tg("tg", "Tajik"),
	th("th", "Thai"),
	ti("ti", "Tigrinya"),
	tk("tk", "Turkmen"),
	tl("tl", "Filipino"),
	tr("tr", "Turkish"),
	ts("ts", "Tsonga"),
	tt("tt", "Tatar"),
	ug("ug", "Uyghur"),
	uk("uk", "Ukrainian"),
	ur("ur", "Urdu"),
	uz("uz", "Uzbek"),
	vi("vi", "Vietnamese"),
	xh("xh", "Xhosa"),
	yi("yi", "Yiddish"),
	yo("yo", "Yoruba"),
	zh("zh", "Chinese"),
	zh_CN("zh-CN", "Chinese (Simplified)"),
	zh_TW("zh-TW", "Chinese (Traditional)"),
	zu("zu", "Zulu");

	private final String code;
	private final String displayName;

	Languages(String code, String displayName)
	{
		this.code = code;
		this.displayName = displayName;
	}

	public String getCode()
	{
		return code;
	}

	public String getDisplayName()
	{
		return displayName;
	}

	@Override
	public String toString()
	{
		return displayName;
	}
}